# Generated by Django 6.0.2 on 2026-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название изделия')),
                ('img', models.ImageField(upload_to='portfolio_img', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dead_line', models.IntegerField(verbose_name='Сроки изготовления в днях')),
            ],
        ),
    ]
